#Requires AutoHotkey v2.0

#Include Helper.ahk

#Include <OCR>

class AutoRecruitConst {
  static DECREMENT_TIMER_HOUR_XY := [480, 320]
  static DECREMENT_TIMER_MINUTE_XY := [655, 320]

  statiC MAX_RARITY := 6
  static MIN_RARITY := 4

  static TAGS_XY := [
    [410, 390], [585, 390], [765, 390],
    [410, 465], [585, 465],
  ]

  static TAG_HEIGHT := 45
  static TAG_WIDTH := 145
}


AutoRecruit() {
  tags := ReadRecruitTags()
  matches := MatchRecruitTags(tags)
  best_combination := GetBestCombination(matches)

  ClickRecruitTags(best_combination)
}

ClickRecruitTags(best_combination) {
  SendMode 'Event'
  SetDefaultMouseSpeed 25
  if best_combination.rarity >= AutoRecruitConst.MIN_RARITY {
    ; click the tags and set timer to max if minimum rarity is equal or greater than MIN_RARITY
    for idx in best_combination.value {
      xy := AutoRecruitConst.TAGS_XY[idx]
      Click xy[1] + AutoRecruitConst.TAG_WIDTH / 2, xy[2] + AutoRecruitConst.TAG_HEIGHT / 2
    }
    Click AutoRecruitConst.DECREMENT_TIMER_HOUR_XY[1], AutoRecruitConst.DECREMENT_TIMER_HOUR_XY[2]
  }
  else {
    ; otherwise, set timer to 7:40:00 (minimum time for getting at least 3★)
    loop 3
      Click AutoRecruitConst.DECREMENT_TIMER_MINUTE_XY[1], AutoRecruitConst.DECREMENT_TIMER_MINUTE_XY[2]

    Click AutoRecruitConst.DECREMENT_TIMER_HOUR_XY[1], AutoRecruitConst.DECREMENT_TIMER_HOUR_XY[2]
  }
}

GetBestCombination(matches) {
  best_combination := []
  min_rarity := AutoRecruitConst.MIN_RARITY - 1

  for combination, matching_operators in matches {
    combination_min_rarity := AutoRecruitConst.MAX_RARITY
    for operator in matching_operators
      combination_min_rarity := Min(combination_min_rarity, operator.rarity)

    combination_arr := StrSplit(combination, '|')
    if (
      ; replace the last best combination if current combination minimum rarity is higher
      combination_min_rarity > min_rarity || (
        ; or if it has the same rarity, but with fewer tag combinations
        combination_min_rarity == min_rarity
        && combination_arr.Length < best_combination.Length
      )
    ) {
      min_rarity := combination_min_rarity
      best_combination := combination_arr
    }
  }

  return { value: best_combination, rarity: min_rarity }
}

MatchRecruitTags(tags) {
  matches := Map()
  for combination_idx in AutoRecruitData.combinations {
    combination := []
    for idx in combination_idx
      combination.Push tags[idx]

    combination_matches := []
    for operator in AutoRecruitData.operators
      if operator.MatchCombination(combination)
        combination_matches.Push operator

    if combination_matches.Length > 0 {
      matches.Set(ArrayJoin(combination_idx, '|'), combination_matches)
    }
  }

  return matches
}

ReadRecruitTags() {
  tags := []
  for xy in AutoRecruitConst.TAGS_XY
    tags.Push OCR.FromRect(
      xy[1], xy[2],
      AutoRecruitConst.TAG_WIDTH, AutoRecruitConst.TAG_HEIGHT,
      'en-US', 2.5
    ).Text

  return tags
}

class Operator {
  __New(name, rarity, tags) {
    this.name := name
    this.rarity := rarity
    this.tags := tags
  }

  MatchCombination(tag_combination) {
    if this.rarity == 6 ; 6★ needs top operator tag
      && !ArrayIncludes(tag_combination, "Top Operator")
      return false

    for tag in tag_combination
      if !ArrayIncludes(this.tags, tag)
        return false

    return true
  }
}

; --- everything below is automatically generated by scripts/fetch_recruit_data.py

; Last updated: 2024-05-26
class AutoRecruitData {
  static combinations := [
    [1], [2], [3], [4], [5],
    [1, 2], [1, 3], [1, 4], [1, 5], [2, 3], [2, 4], [2, 5], [3, 4], [3, 5], [4, 5],
    [1, 2, 3], [1, 2, 4], [1, 2, 5], [1, 3, 4], [1, 3, 5], [1, 4, 5], [2, 3, 4], [2, 3, 5], [2, 4, 5], [3, 4, 5],
  ]

  static operators := [
    Operator('"Justice Knight"', 1, ['Sniper', 'Robot', 'Ranged', 'Robot', 'Support']),
    Operator('Castle-3', 1, ['Guard', 'Robot', 'Melee', 'Robot', 'Support']),
    Operator('Friston-3', 1, ['Defender', 'Robot', 'Melee', 'Robot', 'Defense']),
    Operator('Lancet-2', 1, ['Medic', 'Robot', 'Ranged', 'Robot', 'Healing']),
    Operator('Thermal-EX', 1, ['Specialist', 'Robot', 'Melee', 'Robot', 'Nuker']),
    Operator('12F', 2, ['Caster', 'Ranged', 'Starter']),
    Operator('Durin', 2, ['Caster', 'Ranged', 'Starter']),
    Operator('Noir Corne', 2, ['Defender', 'Melee', 'Starter']),
    Operator('Rangers', 2, ['Sniper', 'Ranged', 'Starter']),
    Operator('Yato', 2, ['Vanguard', 'Melee', 'Starter']),
    Operator('Adnachiel', 3, ['Sniper', 'Ranged', 'DPS']),
    Operator('Ansel', 3, ['Medic', 'Ranged', 'Healing']),
    Operator('Beagle', 3, ['Defender', 'Melee', 'Defense']),
    Operator('Catapult', 3, ['Sniper', 'Ranged', 'AoE']),
    Operator('Fang', 3, ['Vanguard', 'Melee', 'DP-Recovery']),
    Operator('Hibiscus', 3, ['Medic', 'Ranged', 'Healing']),
    Operator('Kroos', 3, ['Sniper', 'Ranged', 'DPS']),
    Operator('Lava', 3, ['Caster', 'Ranged', 'AoE']),
    Operator('Melantha', 3, ['Guard', 'Melee', 'DPS', 'Survival']),
    Operator('Midnight', 3, ['Guard', 'Melee', 'DPS']),
    Operator('Orchid', 3, ['Supporter', 'Ranged', 'Slow']),
    Operator('Plume', 3, ['Vanguard', 'Melee', 'DPS', 'DP-Recovery']),
    Operator('Popukar', 3, ['Guard', 'Melee', 'AoE', 'Survival']),
    Operator('Spot', 3, ['Defender', 'Melee', 'Defense', 'Healing']),
    Operator('Steward', 3, ['Caster', 'Ranged', 'DPS']),
    Operator('Vanilla', 3, ['Vanguard', 'Melee', 'DP-Recovery']),
    Operator('Aciddrop', 4, ['Sniper', 'Ranged', 'DPS']),
    Operator('Ambriel', 4, ['Sniper', 'Ranged', 'DPS', 'Slow']),
    Operator('Beehunter', 4, ['Guard', 'Melee', 'DPS']),
    Operator('Click', 4, ['Caster', 'Ranged', 'DPS', 'Crowd Control']),
    Operator('Cuora', 4, ['Defender', 'Melee', 'Defense']),
    Operator('Cutter', 4, ['Guard', 'Melee', 'Nuker', 'DPS']),
    Operator('Dobermann', 4, ['Guard', 'Melee', 'DPS', 'Support']),
    Operator('Earthspirit', 4, ['Supporter', 'Ranged', 'Slow']),
    Operator('Estelle', 4, ['Guard', 'Melee', 'AoE', 'Survival']),
    Operator('Frostleaf', 4, ['Guard', 'Melee', 'Slow', 'DPS']),
    Operator('Gitano', 4, ['Caster', 'Ranged', 'AoE']),
    Operator('Gravel', 4, ['Specialist', 'Melee', 'Fast-Redeploy', 'Defense']),
    Operator('Greyy', 4, ['Caster', 'Ranged', 'AoE', 'Slow']),
    Operator('Gum', 4, ['Defender', 'Melee', 'Defense', 'Healing']),
    Operator('Haze', 4, ['Caster', 'Ranged', 'DPS', 'Debuff']),
    Operator('Jaye', 4, ['Specialist', 'Melee', 'Fast-Redeploy', 'DPS']),
    Operator('Jessica', 4, ['Sniper', 'Ranged', 'DPS', 'Survival']),
    Operator('Matoimaru', 4, ['Guard', 'Melee', 'Survival', 'DPS']),
    Operator('Matterhorn', 4, ['Defender', 'Melee', 'Defense']),
    Operator('May', 4, ['Sniper', 'Ranged', 'DPS', 'Slow']),
    Operator('Meteor', 4, ['Sniper', 'Ranged', 'DPS', 'Debuff']),
    Operator('Mousse', 4, ['Guard', 'Melee', 'DPS']),
    Operator('Myrrh', 4, ['Medic', 'Ranged', 'Healing']),
    Operator('Myrtle', 4, ['Vanguard', 'Melee', 'DP-Recovery', 'Healing']),
    Operator('Perfumer', 4, ['Medic', 'Ranged', 'Healing']),
    Operator('Podenco', 4, ['Supporter', 'Ranged', 'Slow', 'Healing']),
    Operator('Purestream', 4, ['Medic', 'Ranged', 'Healing', 'Support']),
    Operator('Rope', 4, ['Specialist', 'Melee', 'Shift']),
    Operator('Scavenger', 4, ['Vanguard', 'Melee', 'DP-Recovery', 'DPS']),
    Operator('Shaw', 4, ['Specialist', 'Melee', 'Shift']),
    Operator('ShiraYuki', 4, ['Sniper', 'Ranged', 'AoE', 'Slow']),
    Operator('Sussurro', 4, ['Medic', 'Ranged', 'Healing']),
    Operator('Utage', 4, ['Guard', 'Melee', 'DPS', 'Survival']),
    Operator('Vermeil', 4, ['Sniper', 'Ranged', 'DPS']),
    Operator('Vigna', 4, ['Vanguard', 'Melee', 'DPS', 'DP-Recovery']),
    Operator('Andreana', 5, ['Sniper', 'Senior Operator', 'Ranged', 'DPS', 'Slow']),
    Operator('Asbestos', 5, ['Defender', 'Senior Operator', 'Melee', 'Defense', 'DPS']),
    Operator('Astesia', 5, ['Guard', 'Senior Operator', 'Melee', 'DPS', 'Defense']),
    Operator('Ayerscarpe', 5, ['Guard', 'Senior Operator', 'Melee', 'DPS', 'AoE']),
    Operator('Beeswax', 5, ['Caster', 'Senior Operator', 'Ranged', 'AoE', 'Defense']),
    Operator('Blue Poison', 5, ['Sniper', 'Senior Operator', 'Ranged', 'DPS']),
    Operator('Broca', 5, ['Guard', 'Senior Operator', 'Melee', 'AoE', 'Survival']),
    Operator('Chiave', 5, ['Vanguard', 'Senior Operator', 'Melee', 'DP-Recovery', 'DPS']),
    Operator('Cliffheart', 5, ['Specialist', 'Senior Operator', 'Melee', 'Shift', 'DPS']),
    Operator('Croissant', 5, ['Defender', 'Senior Operator', 'Melee', 'Defense', 'Shift']),
    Operator('Elysium', 5, ['Vanguard', 'Senior Operator', 'Melee', 'DP-Recovery', 'Support']),
    Operator('Executor', 5, ['Sniper', 'Senior Operator', 'Ranged', 'AoE']),
    Operator('FEater', 5, ['Specialist', 'Senior Operator', 'Melee', 'Shift', 'Slow']),
    Operator('Firewatch', 5, ['Sniper', 'Senior Operator', 'Ranged', 'DPS', 'Nuker']),
    Operator('Flint', 5, ['Guard', 'Senior Operator', 'Melee', 'DPS']),
    Operator('Glaucus', 5, ['Supporter', 'Senior Operator', 'Ranged', 'Slow', 'Crowd Control']),
    Operator('GreyThroat', 5, ['Sniper', 'Senior Operator', 'Ranged', 'DPS']),
    Operator('Hung', 5, ['Defender', 'Senior Operator', 'Melee', 'Defense', 'Healing']),
    Operator('Indra', 5, ['Guard', 'Senior Operator', 'Melee', 'DPS', 'Survival']),
    Operator('Istina', 5, ['Supporter', 'Senior Operator', 'Ranged', 'Slow', 'DPS']),
    Operator('Leizi', 5, ['Caster', 'Senior Operator', 'Ranged', 'DPS']),
    Operator('Leonhardt', 5, ['Caster', 'Senior Operator', 'Ranged', 'AoE', 'Nuker']),
    Operator('Liskarm', 5, ['Defender', 'Senior Operator', 'Melee', 'Defense', 'DPS']),
    Operator('Manticore', 5, ['Specialist', 'Senior Operator', 'Melee', 'DPS', 'Survival']),
    Operator('Mayer', 5, ['Supporter', 'Senior Operator', 'Ranged', 'Summon', 'Crowd Control']),
    Operator('Meteorite', 5, ['Sniper', 'Senior Operator', 'Ranged', 'AoE', 'Debuff']),
    Operator('Nearl', 5, ['Defender', 'Senior Operator', 'Melee', 'Defense', 'Healing']),
    Operator('Nightmare', 5, ['Caster', 'Senior Operator', 'Ranged', 'DPS', 'Healing', 'Slow']),
    Operator('Platinum', 5, ['Sniper', 'Senior Operator', 'Ranged', 'DPS']),
    Operator('Pramanix', 5, ['Supporter', 'Senior Operator', 'Ranged', 'Debuff']),
    Operator('Projekt Red', 5, ['Specialist', 'Senior Operator', 'Melee', 'Fast-Redeploy', 'Crowd Control']),
    Operator('Provence', 5, ['Sniper', 'Senior Operator', 'Ranged', 'DPS']),
    Operator('Ptilopsis', 5, ['Medic', 'Senior Operator', 'Ranged', 'Healing', 'Support']),
    Operator('Reed', 5, ['Vanguard', 'Senior Operator', 'Melee', 'DP-Recovery', 'DPS']),
    Operator('Sesa', 5, ['Sniper', 'Senior Operator', 'Ranged', 'AoE', 'Debuff']),
    Operator('Shamare', 5, ['Supporter', 'Senior Operator', 'Ranged', 'Debuff']),
    Operator('Silence', 5, ['Medic', 'Senior Operator', 'Ranged', 'Healing']),
    Operator('Specter', 5, ['Guard', 'Senior Operator', 'Melee', 'AoE', 'Survival']),
    Operator('Swire', 5, ['Guard', 'Senior Operator', 'Melee', 'DPS', 'Support']),
    Operator('Texas', 5, ['Vanguard', 'Senior Operator', 'Melee', 'DP-Recovery', 'Crowd Control']),
    Operator('Tsukinogi', 5, ['Supporter', 'Senior Operator', 'Ranged', 'Support', 'Survival']),
    Operator('Vulcan', 5, ['Defender', 'Senior Operator', 'Melee', 'Survival', 'Defense', 'DPS']),
    Operator('Waai Fu', 5, ['Specialist', 'Senior Operator', 'Melee', 'Fast-Redeploy', 'Debuff']),
    Operator('Warfarin', 5, ['Medic', 'Senior Operator', 'Ranged', 'Healing', 'Support']),
    Operator('Zima', 5, ['Vanguard', 'Senior Operator', 'Melee', 'DP-Recovery', 'Support']),
    Operator('Aak', 6, ['Specialist', 'Top Operator', 'Ranged', 'Support', 'DPS']),
    Operator('Bagpipe', 6, ['Vanguard', 'Top Operator', 'Melee', 'DP-Recovery', 'DPS']),
    Operator('Blaze', 6, ['Guard', 'Top Operator', 'Melee', 'DPS', 'Survival']),
    Operator('Ceobe', 6, ['Caster', 'Top Operator', 'Ranged', 'DPS', 'Crowd Control']),
    Operator("Ch'en", 6, ['Guard', 'Top Operator', 'Melee', 'Nuker', 'DPS']),
    Operator('Eunectes', 6, ['Defender', 'Top Operator', 'Melee', 'DPS', 'Survival', 'Defense']),
    Operator('Exusiai', 6, ['Sniper', 'Top Operator', 'Ranged', 'DPS']),
    Operator('Hellagur', 6, ['Guard', 'Top Operator', 'Melee', 'DPS', 'Survival']),
    Operator('Hoshiguma', 6, ['Defender', 'Top Operator', 'Melee', 'Defense', 'DPS']),
    Operator('Ifrit', 6, ['Caster', 'Top Operator', 'Ranged', 'AoE', 'Debuff']),
    Operator('Magallan', 6, ['Supporter', 'Top Operator', 'Ranged', 'Support', 'Slow', 'DPS']),
    Operator('Mostima', 6, ['Caster', 'Top Operator', 'Ranged', 'AoE', 'Support', 'Crowd Control']),
    Operator('Nightingale', 6, ['Medic', 'Top Operator', 'Ranged', 'Healing', 'Support']),
    Operator('Phantom', 6, ['Specialist', 'Top Operator', 'Melee', 'Fast-Redeploy', 'Crowd Control', 'DPS']),
    Operator('Rosa', 6, ['Sniper', 'Top Operator', 'Ranged', 'DPS', 'Crowd Control']),
    Operator('Saria', 6, ['Defender', 'Top Operator', 'Melee', 'Defense', 'Healing', 'Support']),
    Operator('Schwarz', 6, ['Sniper', 'Top Operator', 'Ranged', 'DPS']),
    Operator('Shining', 6, ['Medic', 'Top Operator', 'Ranged', 'Healing', 'Support']),
    Operator('Siege', 6, ['Vanguard', 'Top Operator', 'Melee', 'DP-Recovery', 'DPS']),
    Operator('SilverAsh', 6, ['Guard', 'Top Operator', 'Melee', 'DPS', 'Support']),
    Operator('Skadi', 6, ['Guard', 'Top Operator', 'Melee', 'DPS', 'Survival']),
    Operator('Suzuran', 6, ['Supporter', 'Top Operator', 'Ranged', 'Slow', 'Support', 'DPS']),
    Operator('Thorns', 6, ['Guard', 'Top Operator', 'Melee', 'DPS', 'Defense']),
    Operator('Weedy', 6, ['Specialist', 'Top Operator', 'Melee', 'Shift', 'DPS', 'Crowd Control']),
  ]
}
